Repository FACN3/easyRep, pull requests merged in 2018-02, with the labels that each got.

#22 Database
  .gitignore
  app.js
  client/README.md
  controllers/createReport.js
  models/Reports.js
  models/Users.js
  package-lock.json
  package.json
  routes/reportRoutes.js
Labels: enhancement, priority-1

#28 Location drop down menu
  client/package.json
  client/public/style.css
  client/src/App.js
  client/src/actions/index.js
  client/src/actions/types.js
  client/src/containers/LocationForm.js
  client/src/location_data.js
  client/src/reducers/index.js
  client/src/reducers/locationReducer.js
  package-lock.json
Labels: priority-2

#32 Got rid of the random 4
  client/src/App.js
Labels: priority-1

#38 Oauth
  .gitignore
  client/package.json
  client/src/App.js
  client/src/components/AuthNavbar.js
  client/src/components/Landing.js
  client/src/components/Login.js
  client/src/components/Navbar.js
  client/src/components/ViewReports.js
  client/src/containers/CategoryForm.js
  client/src/containers/LocationForm.js
  client/src/containers/ReviewForm.js
  client/src/containers/SymptomsForm.js
  client/src/containers/UploadForm.js
  config/dev.js
  config/keys.js
  config/prod.js
  package-lock.json
  package.json
  server/app.js
  server/middlewares/requireLogin.js
  server/models/Users.js
  server/routes/authRoutes.js
  server/routes/reportRoutes.js
  server/services/passport.js
Labels: awaiting-review
